[package]
name = "frontend"
version = "0.1.0"
edition = "2021"

[build]
# The browser JS/WASM are loaded from here
site-pkg-dir = "pkg"
# The source CSS file. cargo-leptos will process this with the given stylesheet engine (currently tailwind)
style-file = "style.css"
# The JS/WASM bundle name. Defaults to the package name
app-name = "frontend"
# The site root directory is where cargo-leptos generate all output. WARNING: all contents of this directory will be overwritten on rebuild.
site-root = "target/site"
# The site-root of the app, served by cargo-leptos. Typically the site-root folder.
site-pkg-url = "/pkg"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
panic = "abort"

